
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/root/miniconda3/envs/cmake-tutorial/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 5.10.16.3-microsoft-standard-WSL2 - x86_64
...
